// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// draw_gig_rcpp_cpp
Rcpp::NumericVector draw_gig_rcpp_cpp(const int n, const double lambda, const double chi, const double psi);
RcppExport SEXP _BayesLinReg_draw_gig_rcpp_cpp(SEXP nSEXP, SEXP lambdaSEXP, SEXP chiSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type chi(chiSEXP);
    Rcpp::traits::input_parameter< const double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_gig_rcpp_cpp(n, lambda, chi, psi));
    return rcpp_result_gen;
END_RCPP
}
// blm_gibbs_rcpp_cpp
Rcpp::List blm_gibbs_rcpp_cpp(const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& X, const Rcpp::NumericVector& prior_var, const double residual_shape, const double residual_scale, const int iterations, const int burnin, const int thin, const Rcpp::Function& progress_callback, const Rcpp::IntegerVector& block_id, const Rcpp::IntegerVector& block_model, const Rcpp::NumericVector& pi_alpha, const Rcpp::NumericVector& pi_beta, const Rcpp::NumericVector& global_scale, const Rcpp::NumericVector& local_a, const Rcpp::NumericVector& local_b, const bool learn_residual_var, const double fixed_residual_var);
RcppExport SEXP _BayesLinReg_blm_gibbs_rcpp_cpp(SEXP ySEXP, SEXP XSEXP, SEXP prior_varSEXP, SEXP residual_shapeSEXP, SEXP residual_scaleSEXP, SEXP iterationsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP progress_callbackSEXP, SEXP block_idSEXP, SEXP block_modelSEXP, SEXP pi_alphaSEXP, SEXP pi_betaSEXP, SEXP global_scaleSEXP, SEXP local_aSEXP, SEXP local_bSEXP, SEXP learn_residual_varSEXP, SEXP fixed_residual_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prior_var(prior_varSEXP);
    Rcpp::traits::input_parameter< const double >::type residual_shape(residual_shapeSEXP);
    Rcpp::traits::input_parameter< const double >::type residual_scale(residual_scaleSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type progress_callback(progress_callbackSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_id(block_idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_model(block_modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pi_alpha(pi_alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pi_beta(pi_betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type global_scale(global_scaleSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type local_a(local_aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type local_b(local_bSEXP);
    Rcpp::traits::input_parameter< const bool >::type learn_residual_var(learn_residual_varSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_residual_var(fixed_residual_varSEXP);
    rcpp_result_gen = Rcpp::wrap(blm_gibbs_rcpp_cpp(y, X, prior_var, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, pi_alpha, pi_beta, global_scale, local_a, local_b, learn_residual_var, fixed_residual_var));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesLinReg_draw_gig_rcpp_cpp", (DL_FUNC) &_BayesLinReg_draw_gig_rcpp_cpp, 4},
    {"_BayesLinReg_blm_gibbs_rcpp_cpp", (DL_FUNC) &_BayesLinReg_blm_gibbs_rcpp_cpp, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesLinReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
