# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_gig_rcpp_cpp <- function(n, lambda, chi, psi) {
    .Call(`_BayesLinReg_draw_gig_rcpp_cpp`, n, lambda, chi, psi)
}

blm_gibbs_rcpp_cpp <- function(y, X, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, slab_shape, slab_scale, global_scale, local_a, local_b, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean) {
    .Call(`_BayesLinReg_blm_gibbs_rcpp_cpp`, y, X, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, slab_shape, slab_scale, global_scale, local_a, local_b, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean)
}

