# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_gig_rcpp_cpp <- function(n, lambda, chi, psi) {
    .Call(`_blm_draw_gig_rcpp_cpp`, n, lambda, chi, psi)
}

blm_gibbs_rcpp_cpp <- function(y, X, prior_var, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, pi_alpha, pi_beta, global_scale, local_a, local_b, learn_residual_var, fixed_residual_var) {
    .Call(`_blm_blm_gibbs_rcpp_cpp`, y, X, prior_var, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, pi_alpha, pi_beta, global_scale, local_a, local_b, learn_residual_var, fixed_residual_var)
}

